import './js/service-api';
import './js/pagination';
import './js/galleryCard';
import './js/modal';
//import './js/teamModal';
import './js/scroll';
import './js/search-by-keyword';
import './js/themeSwitcher';
import './js/firebase/auth-modal';
import './js/firebase/auth-modal-refs';
import './js/firebase/database-api';
import './js/firebase/firebase-init';
import './js/firebase/firebase-auth-home';
import './js/header'
import '../node_modules/basiclightbox/dist/basicLightbox.min.css';
